<!-- 
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
  <el-form :model="formData" ref="vForm" :rules="rules" label-position="left" label-width="80px"
    size="default" @submit.prevent>
    <div class="tab-container">
      <el-tabs v-model="tab44898ActiveTab" type="border-card">
        <el-tab-pane name="tab1" label="node">
          <div class="card-container">
            <el-card style="{width: 100% !important}" shadow="never">
              <template #header>
                <div class="clear-fix">
                  <span>node</span>
                  <i class="float-right el-icon-arrow-down"></i>
                </div>
              </template>
              <el-form-item label="id" prop="input97925">
                <el-input v-model="formData.input97925" type="text" clearable></el-input>
              </el-form-item>
              <el-form-item label="coords" prop="input47426">
                <el-input v-model="formData.input47426" type="text" clearable></el-input>
              </el-form-item>
              <el-form-item label="response level" label-width="100px" prop="select75450">
                <el-select v-model="formData.select75450" class="full-width-input" clearable>
                  <el-option v-for="(item, index) in select75450Options" :key="index" :label="item.label"
                    :value="item.value" :disabled="item.disabled"></el-option>
                </el-select>
              </el-form-item>
              <el-form-item label="switch" prop="switch95811">
                <el-switch v-model="formData.switch95811"></el-switch>
              </el-form-item>
              <div class="static-content-item">
                <el-button>插入</el-button>
              </div>
                <div class="static-content-item">
                <el-button>删除</el-button>
              </div>
              <div class="static-content-item">
                <el-button>修改</el-button>
              </div>
              <div class="static-content-item">
                <el-button>查询</el-button>
              </div>
              <div class="static-content-item">
                <el-button>重置</el-button>
              </div>

            </el-card>
          </div>
        </el-tab-pane>
        <el-tab-pane name="tab-pane-103509" label="sensor">
          <div class="card-container">
            <el-card style="{width: 100% !important}" shadow="never">
              <template #header>
                <div class="clear-fix">
                  <span>sensor</span>
                  <i class="float-right el-icon-arrow-down"></i>
                </div>
              </template>
              <el-form-item label="id" prop="input80886">
                <el-input v-model="formData.input80886" type="text" clearable></el-input>
              </el-form-item>
              <el-form-item label="node" prop="input72452">
                <el-input v-model="formData.input72452" type="text" clearable></el-input>
              </el-form-item>
              <el-form-item label="model" prop="input28330">
                <el-input v-model="formData.input28330" type="text" clearable></el-input>
              </el-form-item>
              <el-form-item label="parameter" prop="select25088">
                <el-select v-model="formData.select25088" class="full-width-input" clearable>
                  <el-option v-for="(item, index) in select25088Options" :key="index" :label="item.label"
                    :value="item.value" :disabled="item.disabled"></el-option>
                </el-select>
              </el-form-item>
              <el-form-item label="upload" prop="switch72193">
                <el-switch v-model="formData.switch72193"></el-switch>
              </el-form-item>
              <div class="static-content-item">
                <el-button>插入</el-button>
              </div>
              <div class="static-content-item">
                <el-button>删除</el-button>
              </div>
              <div class="static-content-item">
                <el-button>修改</el-button>
              </div>
              <div class="static-content-item">
                <el-button>查询</el-button>
              </div>
              <div class="static-content-item">
                <el-button>重置</el-button>
              </div>
            </el-card>
          </div>
        </el-tab-pane>
        <el-tab-pane name="tab-pane-61008" label="data">
          <div class="card-container">
            <el-card style="{width: 100% !important}" shadow="never">
              <template #header>
                <div class="clear-fix">
                  <span>data</span>
                  <i class="float-right el-icon-arrow-down"></i>
                </div>
              </template>
              <el-form-item label="id" prop="input24843">
                <el-input v-model="formData.input24843" type="text" clearable></el-input>
              </el-form-item>
              <el-form-item label="value" prop="input92738">
                <el-input v-model="formData.input92738" type="text" clearable></el-input>
              </el-form-item>
              <el-form-item label="sensor" prop="input59670">
                <el-input v-model="formData.input59670" type="text" clearable></el-input>
              </el-form-item>
              <el-form-item label="date-range" prop="daterange38191">
                <el-date-picker is-range v-model="formData.daterange38191" type="daterange"
                  class="full-width-input" format="YYYY-MM-DD" value-format="YYYY-MM-DD" clearable>
                </el-date-picker>
              </el-form-item>
              <el-form-item label="time-range" prop="timerange93112">
                <el-time-picker is-range v-model="formData.timerange93112" class="full-width-input"
                  format="HH:mm:ss" value-format="HH:mm:ss" clearable></el-time-picker>
              </el-form-item>
              <el-form-item label="raw" prop="input56699">
                <el-input v-model="formData.input56699" type="text" clearable></el-input>
              </el-form-item>
              <el-form-item label="verify" prop="input89184">
                <el-input v-model="formData.input89184" type="text" clearable></el-input>
              </el-form-item>
              <div class="static-content-item">
                <el-button>插入</el-button>
              </div>
              <div class="static-content-item">
                <el-button>删除</el-button>
              </div>
              <div class="static-content-item">
                <el-button>修改</el-button>
              </div>
              <div class="static-content-item">
                <el-button>查询</el-button>
              </div>
              <div class="static-content-item">
                <el-button>重置</el-button>
              </div>
            </el-card>
          </div>
        </el-tab-pane>
        <el-tab-pane name="tab-pane-10159" label="log">
          <div class="card-container">
            <el-card style="{width: 100% !important}" shadow="never">
              <template #header>
                <div class="clear-fix">
                  <span>log</span>
                  <i class="float-right el-icon-arrow-down"></i>
                </div>
              </template>
              <el-form-item label="event" prop="input72266">
                <el-input v-model="formData.input72266" type="text" clearable></el-input>
              </el-form-item>
              <el-form-item label="level" prop="input116618">
                <el-input v-model="formData.input116618" type="text" clearable></el-input>
              </el-form-item>
              <div class="static-content-item">
                <el-button>查询</el-button>
              </div>
              <div class="static-content-item">
                <el-button>增加</el-button>
              </div>
              <div class="static-content-item">
                <el-button>删除</el-button>
              </div>
              <div class="static-content-item">
                <el-button>重置</el-button>
              </div>
            </el-card>
          </div>
        </el-tab-pane>
      </el-tabs>
    </div>
    <div class="card-container">
      <el-card style="{width: 100% !important}" shadow="never">
        <template #header>
          <div class="clear-fix">
            <span>自定义指令</span>
            <i class="float-right el-icon-arrow-down"></i>
          </div>
        </template>
        <el-form-item label="SQL" prop="textarea65656">
          <el-input type="textarea" v-model="formData.textarea65656" rows="3"></el-input>
        </el-form-item>
        <div class="static-content-item">
          <el-button>执行</el-button>
        </div>
      </el-card>
    </div>
    <div class="tab-container">
      <el-tabs v-model="tab52799ActiveTab" type="border-card">
        <el-tab-pane name="tab1" label="数据批量导入">
          <div class="card-container">
            <el-card style="{width: 100% !important}" shadow="never">
              <template #header>
                <div class="clear-fix">
                  <span>数据批量导入</span>
                  <i class="float-right el-icon-arrow-down"></i>
                </div>
              </template>
              <el-form-item label="table" label-width="100px" prop="select60282">
                <el-select v-model="formData.select60282" class="full-width-input" clearable>
                  <el-option v-for="(item, index) in select60282Options" :key="index" :label="item.label"
                    :value="item.value" :disabled="item.disabled"></el-option>
                </el-select>
              </el-form-item>
              <el-form-item label="file-upload" prop="fileupload49665">
                <el-upload :file-list="fileupload49665FileList" :headers="fileupload49665UploadHeaders"
                  :data="fileupload49665UploadData" list-type="picture-card" show-file-list :limit="3">
                  <template #default><i class="el-icon-plus"></i></template></el-upload>
              </el-form-item>
              <div class="static-content-item">
                <el-button>确定</el-button>
              </div>
            </el-card>
          </div>
        </el-tab-pane>
        <el-tab-pane name="tab-pane-99304" label="数据导出">
          <div class="card-container">
            <el-card style="{width: 100% !important}" shadow="never">
              <template #header>
                <div class="clear-fix">
                  <span>数据导出（暂未实现）</span>
                  <i class="float-right el-icon-arrow-down"></i>
                </div>
              </template>
              <el-form-item label="数据类型" prop="select89437">
                <el-select v-model="formData.select89437" class="full-width-input" clearable>
                  <el-option v-for="(item, index) in select89437Options" :key="index" :label="item.label"
                    :value="item.value" :disabled="item.disabled"></el-option>
                </el-select>
              </el-form-item>
              <el-form-item label="date-range" prop="daterange67782">
                <el-date-picker is-range v-model="formData.daterange67782" type="daterange"
                  class="full-width-input" format="YYYY-MM-DD" value-format="YYYY-MM-DD" clearable>
                </el-date-picker>
              </el-form-item>
              <el-form-item label="time-range" prop="timerange15121">
                <el-time-picker is-range v-model="formData.timerange15121" class="full-width-input"
                  format="HH:mm:ss" value-format="HH:mm:ss" clearable></el-time-picker>
              </el-form-item>
              <div class="static-content-item">
                <el-button>导出</el-button>
              </div>
            </el-card>
          </div>
        </el-tab-pane>
      </el-tabs>
    </div>
    <el-form-item label="Results" prop="textarea67004" class="label-center-align">
      <el-input type="textarea" v-model="formData.textarea67004" rows="3"></el-input>
    </el-form-item>
  </el-form>
  
</template>

<script>
  import {
    defineComponent,
    toRefs,
    reactive,
    getCurrentInstance
  }
  from 'vue'
  export default defineComponent({
    components: {},
    props: {},
    setup() {
      const state = reactive({
        formData: {
          input97925: "",
          input47426: "",
          select75450: 2,
          switch95811: false,
          input80886: "",
          input72452: "",
          input28330: "",
          select25088: "",
          switch72193: false,
          input24843: "",
          input92738: "",
          input59670: "",
          daterange38191: null,
          timerange93112: null,
          input56699: "",
          input89184: "",
          input72266: "",
          input116618: "",
          textarea65656: "",
          select60282: 1,
          fileupload49665: null,
          select89437: 1,
          daterange67782: null,
          timerange15121: null,
          textarea67004: "",
        },
        rules: {},
        'tab44898ActiveTab': 'tab1',
        'tab52799ActiveTab': 'tab1',
        select75450Options: [{
          "label": "1",
          "value": 1
        }, {
          "label": "2",
          "value": "2"
        }, {
          "label": "3",
          "value": 3
        }],
        select25088Options: [{
          "label": "select 1",
          "value": 1
        }, {
          "label": "select 2",
          "value": 2
        }, {
          "label": "select 3",
          "value": 3
        }],
        select60282Options: [{
          "label": "node",
          "value": 1
        }, {
          "label": "sensor",
          "value": 2
        }, {
          "label": "data",
          "value": "3"
        }],
        select89437Options: [{
          "label": "温度",
          "value": 1
        }, {
          "label": "select 2",
          "value": 2
        }, {
          "label": "select 3",
          "value": 3
        }],
        fileupload49665FileList: [],
        fileupload49665UploadHeaders: {},
        fileupload49665UploadData: {},
      })
      const instance = getCurrentInstance()
      const submitForm = () => {
        instance.ctx.$refs['vForm'].validate(valid => {
          if (!valid) return
          //TODO: 提交表单
        })
      }
      const resetForm = () => {
        instance.ctx.$refs['vForm'].resetFields()
      }
      return {
        ...toRefs(state),
        submitForm,
        resetForm
      }
    }
  })
  
</script>

<style lang="scss">
  .el-input-number.full-width-input,
  .el-cascader.full-width-input {
    width: 100% !important;
  }
  
  .el-form-item--medium {
    .el-radio {
      line-height: 36px !important;
    }
    
    .el-rate {
      margin-top: 8px;
    }
  }
  
  .el-form-item--small {
    .el-radio {
      line-height: 32px !important;
    }
    
    .el-rate {
      margin-top: 6px;
    }
  }
  
  .el-form-item--mini {
    .el-radio {
      line-height: 28px !important;
    }
    
    .el-rate {
      margin-top: 4px;
    }
  }
  
  .clear-fix:before,
  .clear-fix:after {
    display: table;
    content: "";
  }
  
  .clear-fix:after {
    clear: both;
  }
  
  .float-right {
    float: right;
  }
  

</style>

<style lang="scss" scoped>
  div.table-container {
    table.table-layout {
      width: 100%;
      table-layout: fixed;
      border-collapse: collapse;

      td.table-cell {
        display: table-cell;
        height: 36px;
        border: 1px solid #e1e2e3;
      }
    }
  }
  
  div.tab-container {}
  
  .label-left-align :deep(.el-form-item__label) {
    text-align: left;
  }
  
  .label-center-align :deep(.el-form-item__label) {
    text-align: center;
  }
  
  .label-right-align :deep(.el-form-item__label) {
    text-align: right;
  }
  
  .custom-label {}
  
  .static-content-item {
    min-height: 20px;
    display: inline-flex;
    align-items: center;
    margin-right: 10px;

    :deep(.el-divider--horizontal) {
      margin: 0;
    }
  }


  
</style>